name: Deploy to Cloud Run

on:
  pull_request:
    branches: [ backend-release ]

jobs:
  build_image:
  
    name: Build Docker image (Flask-app) # name of the job

    runs-on: ubuntu-latest # This job will run on ubuntu virtual machine
    
    env:
      working-directory: ./backend

    steps:
      - name: checkout code
        uses: actions/checkout@v2 #checkout the repo

      - run: docker build -t flask_app .
        working-directory: ${{env.working-directory}}

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: docker tag flask_app dexter94/docker_monitor_api
        working-directory: ${{env.working-directory}}
    
      # - run: docker push dexter94/docker_monitor_api
      #   working-directory: ${{env.working-directory}}

  deploy_cloud:
    needs: build_image

    name: Deploy to Cloud Run
    
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      RUN_REGION: europe-west2
      SA_KEY_JSON: ${{ secrets.GCP_SA_KEY }}
      working-directory: ./backend

    steps:
      - name: install python 2.7
        run: |
          sudo apt-get install python2.7
          export CLOUDSDK_PYTHON="usr/bin/python2"
        working-directory: ${{env.working-directory}}

      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA
        working-directory: ${{env.working-directory}}

    # steps:

    # - name: Setup gcloud CLI
    #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     version: "290.0.1"
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     project_id: ${{ secrets.GCP_PROJECT }}


    # - name: Deploy
    #   run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA --platform managed --region $RUN_REGION
