name: flutter_ci

on:
  push:
    branches: [ front-release ]
  pull_request:
    branches: [ front-release ]
  
jobs:
  build_web:

    name: Build Flutter (Web) # name of the job
    
    runs-on: ubuntu-latest # This job will run on ubuntu virtual machine

    #setup the working env where to run the commands
    env:
      working-directory: ./front
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:

    - uses: actions/checkout@v1
    
    - uses: subosito/flutter-action@v1 # flutter environment to use in GitHub Actions
      with:
        channel: 'dev'
    
    - run: flutter pub get # get dependencies of the project
      working-directory: ${{env.working-directory}}
    
    - run: flutter config --enable-web
      working-directory: ${{env.working-directory}}
      
    # Check for any formatting issues in the code
    # - run: flutter format --set-exit-if-changed .
    #  working-directory: ${{env.working-directory}}

    - run: flutter build web  # Build application for web
      working-directory: ${{env.working-directory}}
    
    - run: curl -sL firebase.tools | bash
      working-directory: ${{env.working-directory}}
      
    - run: firebase deploy --token "$FIREBASE_TOKEN" 
      working-directory: ${{env.working-directory}}
      
    # - run: bash firebase deploy --token $FIREBASE_TOKEN # deploy to firebase
    #  working-directory: ${{env.working-directory}}
